"""Fetch CelesTrak group feeds and emit per-constellation data files.

Reuses the exact TLE plumbing of fetch_demo_catalog (same URL, parser, and
element derivation) so constellations share one pipeline with the curated
catalog. Output: frontend/src/data/constellations/<key>.json, lazy-imported
by the engine. Caps are evidence-driven — rerun with --cap after benchmarking.
"""
import argparse
import json
import sys
import urllib.error
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from fetch_demo_catalog import GROUP_URL, get, make_entry, parse_blocks  # noqa: E402

ROOT = Path(__file__).resolve().parents[2]
OUT_DIR = ROOT / "frontend" / "src" / "data" / "constellations"

# key -> (label, [(celesstrak_group, take, description, launched)], total cap)
# Group names verified against the live CelesTrak GP API (2026-10): there is
# no `iridium`/`noaa` group — use `iridium-next`, and the NOAA/constellation
# weather fleet lives in `weather` (GOES, JPSS, MetOp, Himawari, …).
CONSTELLATIONS = {
    "test": ("Validation Set", [("iridium-next", 5, "Cross-link constellation · Iridium NEXT", 2017),
                                ("geo", 3, "GEO comms smoke test", 2010)], 8),
    "gps": ("GPS", [("gps-ops", 31, "Navigation · USSF GPS", 2014)], 31),
    "weather": ("NOAA / Weather", [("weather", 40, "Weather · NOAA / operator", 2000)], 40),
    "starlink": ("Starlink", [("starlink", 5000, "Broadband · SpaceX", 2020)], 120),
}


def get_group(group: str) -> str:
    """Fetch a GP group, refusing to mistake CelesTrak's 2-hour dedupe
    notice for element data (it is a plain-text message, not a TLE)."""
    try:
        text = get(GROUP_URL.format(group=group))
    except urllib.error.HTTPError as exc:
        raise RuntimeError(
            f"CelesTrak refused GROUP={group} (HTTP {exc.code}) — its starlink "
            "group refetches are deduped for 2 h; retry later or use --from-file") from None
    if "GP data has not updated" in text[:200] or "Invalid query" in text[:200]:
        raise RuntimeError(f"CelesTrak refused GROUP={group}: {text.splitlines()[0]}")
    return text


def build(key: str, sources, cap: int, exclude: set[int],
          from_file: dict[str, str] | None = None):
    entries = []
    for group, take, desc, year in sources:
        text = (from_file or {}).get(group) or get_group(group)
        blocks = parse_blocks(text)
        n = 0
        for norad, name, l1, l2 in blocks:
            if norad in exclude or any(e["norad_id"] == norad for e in entries):
                continue
            entries.append(make_entry(key, norad, name, l1, l2, desc, year))
            exclude.add(norad)
            n += 1
            if n >= take or len(entries) >= cap:
                break
        if len(entries) >= cap:
            break
    return entries[:cap]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--key", help="build only this constellation")
    ap.add_argument("--cap", type=int, help="override the configured cap")
    ap.add_argument("--from-file", action="append", default=[],
                    metavar="GROUP=PATH",
                    help="use a previously downloaded TLE text file for GROUP "
                         "(e.g. while CelesTrak's 2-hour dedupe window is closed)")
    args = ap.parse_args()
    from_file = {}
    for pair in args.from_file:
        g, _, p = pair.partition("=")
        from_file[g] = Path(p).read_text(encoding="utf-8", errors="replace")

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    keys = [args.key] if args.key else list(CONSTELLATIONS)
    exclude: set[int] = set()
    # Featured catalog objects must not be duplicated by constellation layers.
    curated = ROOT / "frontend" / "src" / "data" / "satellites.json"
    if curated.exists():
        exclude = {s["norad_id"] for s in json.loads(curated.read_text())["satellites"]}

    for key in keys:
        label, sources, cap = CONSTELLATIONS[key]
        cap = args.cap or cap
        entries = build(key, sources, cap, exclude, from_file)
        if not entries:
            print(f"FAIL {key}: no satellites fetched", file=sys.stderr)
            sys.exit(1)
        payload = {
            "key": key,
            "label": label,
            "source": "celestrak",
            "fetched_at": datetime.now(timezone.utc).isoformat(),
            "note": f"Generated by backend/tools/fetch_constellations.py (cap {cap})",
            "satellites": entries,
        }
        out = OUT_DIR / f"{key}.json"
        out.write_text(json.dumps(payload, indent=1), encoding="utf-8")
        sizes = {e["regime"] for e in entries}
        print(f"ok {key:9s} {len(entries):4d} sats  regimes={sorted(sizes)}  -> {out.name}")


if __name__ == "__main__":
    main()
